# Generated by Django 5.0.3 on 2024-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
    ]
