# Generated by Django 5.0.3 on 2024-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_deadline_alter_todo_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
